# Важно!

Придерживайтесь эталонного вывода в коде каждого задания, чтобы избежать расхождений в трактовках условий задания.

In [2]:
# загрузим библиотеки
import numpy as np
import pandas as pd

## Задание 1

Создайте массив из 100 элементов (от 1 до 100), переформатируйте в формат (10 * 10), сделайте слайсинг с шагом 2 по каждой оси.

In [3]:
np_array = np.arange(1,101)
 
print(f"массив от 1 до 100, 10х10, со слайсингом с шагом 2 по каждой оси:\n {np_array.reshape(10,10)[::2,::2]}")


массив от 1 до 100, 10х10, со слайсингом с шагом 2 по каждой оси:
 [[ 1  3  5  7  9]
 [21 23 25 27 29]
 [41 43 45 47 49]
 [61 63 65 67 69]
 [81 83 85 87 89]]


## Задание 2

Написать функцию, которая по заданной длине последовательности находит среднее арифметическое ее членов. (Для соответсвия примеру вывода используйте длину length = 100_000_000)

Реализуйте задачу с и без помощи numpy, сравните время выполнения

Используйте выражение 


`%%time` 

в первой строчке ячейки кода для отображения времени выполнения ячейки

Если возникамют ошибки с %%time - используйте код

`
from datetime import datetime
start_time = datetime.now()
---ваш код---
print(datetime.now() - start_time)
`

In [4]:
from datetime import datetime

def avg_numpy(length: int = 100_000_000) -> float:
    arr = np.arange(0, length) 
    return np.mean(arr)


print("--- NumPy ---")
start_time = datetime.now()
print("Среднее арифметическое последовательности:", avg_numpy())
print(f"Время: {datetime.now() - start_time} сек\n")



--- NumPy ---
Среднее арифметическое последовательности: 49999999.5
Время: 0:00:00.330439 сек



In [5]:
def avg_pure_python(length: int = 100_000_000) -> float:
    return sum(range(0, length)) / length

print("--- Чистый Python ---")
start_time = datetime.now()
print("Среднее арифметическое последовательности:", avg_pure_python())
print(f"Время: {datetime.now() - start_time} сек")

--- Чистый Python ---
Среднее арифметическое последовательности: 49999999.5
Время: 0:00:02.934743 сек


Если все сделано верно, то можно заметить, что у нампай скорость выполнения заметно выше питона 

## Задание 3

Задан Series объект s, найти индекс первого элемента отсортированного s, где значения больше 5

Изначальный код:

`
r = np.random.RandomState(1)
s=pd.Series(r.uniform(0, 10, 100))
`

In [6]:
# задано изначально
# генерируем один и тот же список
r = np.random.RandomState(1)
s=pd.Series(r.uniform(0, 10, 100))

s_sorted = s.sort_values()
index_first = s_sorted[s_sorted > 5].index[0]
print(f"Индекс первого элемента отсортированного s : {index_first}")




Индекс первого элемента отсортированного s : 67


## Задание 4

Имеется небольшой игрушечный датафрейм, в котором необходимо провести несколько типов фильтраций (ответы ищите в решениях) и отобразить результат:

* всех, кто старше 40
* всех, кто имеет доход выше среднего по датасету
* всех, кто имеет доход выше среднего по датасету, но надежность ниже среднего по датасету

создать новые столбцы:

* важность клиента = доход * надежность
* возможная долгосрочность клиента = важность клиента * (средний возраст по датасету - возраст клиента)

`подсказка: двойные условия записываются так: (условие 1) & (условие 2)`


** примечание: столбцы не имеют отношения к реальным формулам или моделям, они необходимы только для наглядности

In [7]:
# создадим тестовый датасет
df = pd.DataFrame({
    'имя': ['Петя', 'Вася', 'Аня', 'Света'],
    'возраст': [45, 26, 41 , 21],
    'доход': [100000, 80000, 150000, 60000],
    'надежность клиента (0..1)': [0.65, 0.74, 0.87, 0.68],
    'пол': ['муж', 'муж', 'жен', 'жен']},
    index=[0, 1, 2, 3])

print(f"------------------------------------------------------------------------")
print(f"Все, кто старше 40 : \n{df[df['возраст'] > 40]}")
mean_income = df['доход'].mean()
print(f"------------------------------------------------------------------------")
print(f"Средний доход : {mean_income}")
print(f"Все, кто имеет доход выше среднего :\n {df[df['доход'] > mean_income]}")
print(f"------------------------------------------------------------------------")
mean_reliability = df['надежность клиента (0..1)'].mean()
print(f"Средняя надежность : {mean_reliability}")
income_high_reliability_low = df[(df['доход'] > mean_income) & 
                                 (df['надежность клиента (0..1)'] < mean_reliability)]
print(f"Все, кто имеет доход выше среднего, но надежность ниже среднего : \n {income_high_reliability_low}")
print(f"------------------------------------------------------------------------")
df['важность клиента'] = df['доход'] * df['надежность клиента (0..1)']
mean_age = df['возраст'].mean()
print(f"Средний возраст : {mean_age}")
df['возможная долгосрочность клиента'] = df['важность клиента'] * (mean_age - df['возраст'])

print("Обновлённый df:\n", df.to_string())

------------------------------------------------------------------------
Все, кто старше 40 : 
    имя  возраст   доход  надежность клиента (0..1)  пол
0  Петя       45  100000                       0.65  муж
2   Аня       41  150000                       0.87  жен
------------------------------------------------------------------------
Средний доход : 97500.0
Все, кто имеет доход выше среднего :
     имя  возраст   доход  надежность клиента (0..1)  пол
0  Петя       45  100000                       0.65  муж
2   Аня       41  150000                       0.87  жен
------------------------------------------------------------------------
Средняя надежность : 0.7350000000000001
Все, кто имеет доход выше среднего, но надежность ниже среднего : 
     имя  возраст   доход  надежность клиента (0..1)  пол
0  Петя       45  100000                       0.65  муж
------------------------------------------------------------------------
Средний возраст : 33.25
Обновлённый df:
      имя  возраст  

## Задание 5

Используя материалы данных Титаника вывести имена всех выживших детей (до 18 лет) и их количество

Изначальный код:

data = pd.read_csv('https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv')

data.head()

In [8]:
data = pd.read_csv('titanic.csv')

data.head()

Survived  Pclass                                               Name  \
0         0       3                             Mr. Owen Harris Braund   
1         1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2         1       3                              Miss. Laina Heikkinen   
3         1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4         0       3                            Mr. William Henry Allen   

      Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0    male  22.0                        1                        0   7.2500  
1  female  38.0                        1                        0  71.2833  
2  female  26.0                        0                        0   7.9250  
3  female  35.0                        1                        0  53.1000  
4    male  35.0                        0                        0   8.0500

In [9]:
# отображаем количество выживших детей

child_surv = data[(data.Age < 18) & (data.Survived == 1)] 
print(f"Количество выживших детей : {len(child_surv)}")
child_surv

Количество выживших детей : 65


Survived  Pclass                                     Name     Sex    Age  \
9           1       2       Mrs. Nicholas (Adele Achem) Nasser  female  14.00   
10          1       3           Miss. Marguerite Rut Sandstrom  female   4.00   
22          1       3                       Miss. Anna McGowan  female  15.00   
39          1       3               Miss. Jamila Nicola-Yarred  female  14.00   
42          1       2  Miss. Simonne Marie Anne Andree Laroche  female   3.00   
..        ...     ...                                      ...     ...    ...   
826         1       3   Mrs. Antoni (Selini Alexander) Yasbeck  female  15.00   
827         1       2           Master. George Sibley Richards    male   0.83   
849         1       1                 Miss. Mary Conover Lines  female  16.00   
865         1       3           Master. Harold Theodor Johnson    male   4.00   
871         1       3                 Miss. Adele Kiamie Najib  female  15.00   

     Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
9                          1                        0  30.0708  
10                         1                        1  16.7000  
22                         0                        0   8.0292  
39                         1                        0  11.2417  
42                         1                        2  41.5792  
..                       ...                      ...      ...  
826                        1                        0  14.4542  
827                        1                        1  18.7500  
849                        0                        1  39.4000  
865                        1                        1  11.1333  
871                        0                        0   7.2250  

[65 rows x 8 columns]

In [10]:
# отображаем их имена
print("Имена выживших детей:")
child_surv.Name


Имена выживших детей:


9           Mrs. Nicholas (Adele Achem) Nasser
10              Miss. Marguerite Rut Sandstrom
22                          Miss. Anna McGowan
39                  Miss. Jamila Nicola-Yarred
42     Miss. Simonne Marie Anne Andree Laroche
                        ...                   
826     Mrs. Antoni (Selini Alexander) Yasbeck
827             Master. George Sibley Richards
849                   Miss. Mary Conover Lines
865             Master. Harold Theodor Johnson
871                   Miss. Adele Kiamie Najib
Name: Name, Length: 65, dtype: object

In [11]:
#~D:A@G aaah_h_f`_hf